### ISSUE TITLE
关于非标准二维码decode解码失败

### ISSUE THREAD

**Issue by pkjy** [pkjy/qrcode-pure#1]
使用中发现非标准的二维码格式（比如手机截图，其中一块区域是二维码），进行解码的时候会提示解码失败。应该是源码对解码的姿势问题，具体原因待确认。如果有自动识别图片内部二维码需求的可以参考这个库[zxing-js](https://github.com/zxing-js/library)，基于`zxing`（一个各种二维码格式支持特别全的qrcode库，JAVA写的）[zxing传送门](https://github.com/zxing/zxing)，而前面的`zxing-js`是`zxing`的`ts`版，测试了一下还挺好用的。

**Comment by epver** [comment]
我也发现了这个问题, debug了下,应该是定位的问题

**Comment by epver** [comment]
然后将图像旋转之后就无法识别, errorCode 5

**Comment by pkjy** [comment]
目前底层使用的那个库没有具体去看实现方式，包括二维码的定位那块。后来才发现zxing和zxing对应的JS，TS版。TS版能解决我们目前的业务需求，所以如果有需求的可以去看看zxing相关的几个库，挺不错的。 @advsets
